# ═══════════════════════════════════════════════════
# AOS Installer — One command, fully running bot
# ═══════════════════════════════════════════════════
#
# Run from PowerShell (as Administrator for Task Scheduler):
#   irm https://raw.githubusercontent.com/GregMotenJr/aoc/master/install.ps1 | iex
#
# Or from a cloned repo:
#   powershell -ExecutionPolicy Bypass -File install.ps1

$ErrorActionPreference = "Stop"

function ok   { param($msg) Write-Host "✓ $msg" -ForegroundColor Green }
function warn { param($msg) Write-Host "⚠ $msg" -ForegroundColor Yellow }
function fail { param($msg) Write-Host "✗ $msg" -ForegroundColor Red; exit 1 }
function ask  { param($prompt) Read-Host $prompt }

$ProjectRoot = $PSScriptRoot
if (-not $ProjectRoot) { $ProjectRoot = Get-Location }
Set-Location $ProjectRoot

Write-Host ""
Write-Host "╔═══════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║   AOS — Alfred Operating System       ║" -ForegroundColor Cyan
Write-Host "║   One-command installer                ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Platform: Windows" -ForegroundColor White
Write-Host ""

# ─── Step 1: Check prerequisites ──────────────────

Write-Host "Checking prerequisites..." -ForegroundColor White
Write-Host ""

# Node.js
try {
  $nodeVersion = (node -v 2>&1).ToString().TrimStart('v')
  $nodeMajor   = [int]($nodeVersion.Split('.')[0])
  if ($nodeMajor -lt 20) {
    fail "Node.js v$nodeVersion found — AOS requires v20 or higher. Update at https://nodejs.org"
  }
  ok "Node.js v$nodeVersion"
} catch {
  fail "Node.js not found. Install Node.js 20+ from https://nodejs.org"
}

# npm
try {
  $npmVersion = (npm -v 2>&1).ToString()
  ok "npm $npmVersion"
} catch {
  fail "npm not found. It should come with Node.js — reinstall from https://nodejs.org"
}

# Claude CLI
try {
  $claudeVersion = (claude --version 2>&1).ToString()
  ok "Claude CLI $claudeVersion"
} catch {
  warn "Claude CLI not found."
  Write-Host "  AOS uses Claude Code under the hood. Install it with:" -ForegroundColor Yellow
  Write-Host ""
  Write-Host "    npm install -g @anthropic-ai/claude-code" -ForegroundColor Cyan
  Write-Host ""
  Write-Host "  Then run: claude   (to authenticate)" -ForegroundColor Yellow
  Write-Host ""
  $answer = ask "Continue anyway? You can install Claude CLI later. (y/N)"
  if ($answer -notmatch '^[Yy]') {
    Write-Host "Install Claude CLI first, then re-run install.ps1"
    exit 0
  }
}

# ─── Step 2: Install dependencies ─────────────────

Write-Host ""
Write-Host "Installing dependencies..." -ForegroundColor White
Write-Host ""
npm install --no-fund --no-audit
ok "Dependencies installed"

# ─── Step 3: Configure .env ───────────────────────

Write-Host ""
Write-Host "Configuration" -ForegroundColor White
Write-Host ""

$skipEnv = $false
if (Test-Path ".env") {
  Write-Host "  Existing .env file found." -ForegroundColor Yellow
  $answer = ask "  Overwrite it? (y/N)"
  if ($answer -notmatch '^[Yy]') {
    ok "Keeping existing .env"
    $skipEnv = $true
  }
}

if (-not $skipEnv) {
  Write-Host ""
  Write-Host "  You'll need a Telegram bot token. If you don't have one:" -ForegroundColor White
  Write-Host "  1. Open Telegram and search for @BotFather"
  Write-Host "  2. Send /newbot and follow the prompts"
  Write-Host "  3. Copy the token it gives you"
  Write-Host ""

  $botToken = ask "  Telegram bot token"
  if ([string]::IsNullOrWhiteSpace($botToken)) {
    fail "Bot token is required. Get one from @BotFather on Telegram."
  }

  Write-Host ""
  Write-Host "  Optional features (press Enter to skip any):" -ForegroundColor White
  Write-Host ""

  $groqKey         = ask "  Groq API key (voice transcription — https://console.groq.com)"
  $elevenLabsKey   = ask "  ElevenLabs API key (voice replies — https://elevenlabs.io)"
  $elevenLabsVoice = ""
  if (-not [string]::IsNullOrWhiteSpace($elevenLabsKey)) {
    $elevenLabsVoice = ask "  ElevenLabs voice ID"
  }
  $googleKey = ask "  Google API key (video analysis — https://aistudio.google.com)"

  $envContent = @"
# AOS Configuration — generated by install.ps1

# Telegram bot token (from @BotFather)
TELEGRAM_BOT_TOKEN=$botToken

# Your Telegram chat ID
# After starting the bot, send /chatid to it and paste the number here
ALLOWED_CHAT_ID=

# Voice transcription (Groq Whisper) — optional
GROQ_API_KEY=$groqKey

# Voice replies (ElevenLabs TTS) — optional
ELEVENLABS_API_KEY=$elevenLabsKey
ELEVENLABS_VOICE_ID=$elevenLabsVoice

# Video analysis (Google Gemini) — optional
GOOGLE_API_KEY=$googleKey

# Logging
LOG_LEVEL=info
NODE_ENV=production
"@

  $envContent | Set-Content -Path ".env" -Encoding UTF8
  ok ".env configured"
}

# ─── Step 4: Build ────────────────────────────────

Write-Host ""
Write-Host "Building..." -ForegroundColor White
Write-Host ""
npm run build
ok "TypeScript compiled"

# ─── Step 5: Background service (Task Scheduler) ──

Write-Host ""
Write-Host "Setting up background service..." -ForegroundColor White
Write-Host ""

$serviceOk = $false
$nodePath   = (Get-Command node).Source
$scriptPath = Join-Path $ProjectRoot "dist\index.js"
$taskName   = "AOS-Alfred"

try {
  $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator
  )

  if ($isAdmin) {
    # Register as a scheduled task that runs at logon
    $action   = New-ScheduledTaskAction -Execute $nodePath -Argument $scriptPath -WorkingDirectory $ProjectRoot
    $trigger  = New-ScheduledTaskTrigger -AtLogon
    $settings = New-ScheduledTaskSettingsSet -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero)
    $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Limited

    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
      -Settings $settings -Principal $principal -Force | Out-Null

    ok "Task Scheduler service registered (auto-starts at login)"
    $serviceOk = $true
  } else {
    warn "Not running as Administrator — skipping Task Scheduler setup."
    Write-Host "  To register as a background service, re-run as Administrator." -ForegroundColor Yellow
  }
} catch {
  warn "Could not register Task Scheduler task: $_"
}

# ─── Step 6: Heartbeat (Scheduled Task, every 10 min) ─

if ($serviceOk) {
  try {
    $hbScript  = Join-Path $ProjectRoot "scripts\heartbeat.ps1"
    $hbAction  = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NonInteractive -File `"$hbScript`""
    $hbTrigger = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Minutes 10) -RepetitionDuration (New-TimeSpan -Days 9999) -Once -At (Get-Date)
    Register-ScheduledTask -TaskName "AOS-Heartbeat" -Action $hbAction -Trigger $hbTrigger -Force | Out-Null
    ok "Heartbeat monitor registered (checks every 10 minutes)"
  } catch {
    warn "Could not register heartbeat task (non-critical)"
  }
}

# ─── Done ─────────────────────────────────────────

Write-Host ""
Write-Host "═══════════════════════════════════════" -ForegroundColor Green
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "  What to do now:" -ForegroundColor White
Write-Host ""

if ($serviceOk) {
  Write-Host "  1. Start the bot:"
  Write-Host "     Start-ScheduledTask -TaskName '$taskName'" -ForegroundColor Cyan
} else {
  Write-Host "  1. Start the bot:"
  Write-Host "     npm start" -ForegroundColor Cyan
}

Write-Host ""
Write-Host "  2. Open Telegram and send /chatid to your bot"
Write-Host ""
Write-Host "  3. Copy the chat ID and add it to .env:"
Write-Host "     ALLOWED_CHAT_ID=<your_chat_id>" -ForegroundColor Cyan
Write-Host ""

if ($serviceOk) {
  Write-Host "  4. Restart the bot:"
  Write-Host "     Stop-ScheduledTask -TaskName '$taskName'; Start-ScheduledTask -TaskName '$taskName'" -ForegroundColor Cyan
} else {
  Write-Host "  4. Restart the bot: Ctrl+C, then npm start"
}

Write-Host ""
Write-Host "  5. Customize CLAUDE.md with your AI's personality"
Write-Host ""
Write-Host "  6. Send a message — you're live!"
Write-Host ""
