#!/usr/bin/env bash
# ═══════════════════════════════════════════════════
# AOS Installer — One command, fully running bot
# ═══════════════════════════════════════════════════
#
# Usage:
#   git clone https://github.com/GregMotenJr/aoc.git aos
#   cd aos
#   ./install.sh
#
# That's it. This script handles everything else.

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BOLD='\033[1m'
RESET='\033[0m'

ok()   { echo -e "${GREEN}✓${RESET} $1"; }
warn() { echo -e "${YELLOW}⚠${RESET} $1"; }
fail() { echo -e "${RED}✗${RESET} $1"; exit 1; }
ask()  { read -rp "$1" REPLY; echo "$REPLY"; }

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

echo ""
echo -e "${BOLD}╔═══════════════════════════════════════╗"
echo -e "║   AOS — Alfred Operating System       ║"
echo -e "║   One-command installer                ║"
echo -e "╚═══════════════════════════════════════╝${RESET}"
echo ""

# ─── Step 1: Check prerequisites ──────────────────

echo -e "${BOLD}Checking prerequisites...${RESET}"
echo ""

# Node.js
if ! command -v node &>/dev/null; then
  fail "Node.js not found. Install Node.js 20+ from https://nodejs.org"
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
  fail "Node.js v${NODE_VERSION} found — AOS requires v20 or higher. Update at https://nodejs.org"
fi
ok "Node.js $(node -v)"

# npm
if ! command -v npm &>/dev/null; then
  fail "npm not found. It should come with Node.js — reinstall from https://nodejs.org"
fi
ok "npm $(npm -v)"

# Claude CLI
if command -v claude &>/dev/null; then
  ok "Claude CLI $(claude --version 2>/dev/null || echo 'installed')"
else
  echo ""
  warn "Claude CLI not found."
  echo "  AOS uses Claude Code under the hood. Install it with:"
  echo ""
  echo "    npm install -g @anthropic-ai/claude-code"
  echo ""
  echo "  Then run: claude   (to authenticate)"
  echo ""
  ANSWER=$(ask "Continue anyway? You can install Claude CLI later. (y/N): ")
  if [[ ! "$ANSWER" =~ ^[Yy] ]]; then
    echo "Install Claude CLI first, then re-run ./install.sh"
    exit 0
  fi
fi

# ─── Step 2: Install dependencies ─────────────────

echo ""
echo -e "${BOLD}Installing dependencies...${RESET}"
echo ""
npm install --no-fund --no-audit
ok "Dependencies installed"

# ─── Step 3: Configure .env ───────────────────────

echo ""
echo -e "${BOLD}Configuration${RESET}"
echo ""

if [ -f .env ]; then
  echo "  Existing .env file found."
  ANSWER=$(ask "  Overwrite it? (y/N): ")
  if [[ ! "$ANSWER" =~ ^[Yy] ]]; then
    ok "Keeping existing .env"
    SKIP_ENV=1
  fi
fi

if [ "${SKIP_ENV:-0}" != "1" ]; then
  echo ""
  echo "  You'll need a Telegram bot token. If you don't have one:"
  echo "  1. Open Telegram and search for @BotFather"
  echo "  2. Send /newbot and follow the prompts"
  echo "  3. Copy the token it gives you"
  echo ""

  BOT_TOKEN=$(ask "  Telegram bot token: ")
  if [ -z "$BOT_TOKEN" ]; then
    fail "Bot token is required. Get one from @BotFather on Telegram."
  fi

  echo ""
  echo "  Optional features (press Enter to skip any):"
  echo ""

  GROQ_KEY=$(ask "  Groq API key (voice transcription — https://console.groq.com): ")
  ELEVENLABS_KEY=$(ask "  ElevenLabs API key (voice replies — https://elevenlabs.io): ")

  ELEVENLABS_VOICE=""
  if [ -n "$ELEVENLABS_KEY" ]; then
    ELEVENLABS_VOICE=$(ask "  ElevenLabs voice ID: ")
  fi

  GOOGLE_KEY=$(ask "  Google API key (video analysis — https://aistudio.google.com): ")

  cat > .env << EOF
# AOS Configuration — generated by install.sh

# Telegram bot token (from @BotFather)
TELEGRAM_BOT_TOKEN=${BOT_TOKEN}

# Your Telegram chat ID
# After starting the bot, send /chatid to it and paste the number here
ALLOWED_CHAT_ID=

# Voice transcription (Groq Whisper) — optional
GROQ_API_KEY=${GROQ_KEY}

# Voice replies (ElevenLabs TTS) — optional
ELEVENLABS_API_KEY=${ELEVENLABS_KEY}
ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE}

# Video analysis (Google Gemini) — optional
GOOGLE_API_KEY=${GOOGLE_KEY}

# Logging
LOG_LEVEL=info
NODE_ENV=production
EOF

  chmod 600 .env
  ok ".env configured"
fi

# ─── Step 4: Build ────────────────────────────────

echo ""
echo -e "${BOLD}Building...${RESET}"
echo ""
npm run build
ok "TypeScript compiled"

# ─── Step 5: systemd service (Linux only) ─────────

if [ "$(uname)" = "Linux" ]; then
  echo ""
  echo -e "${BOLD}Setting up background service...${RESET}"
  echo ""

  SERVICE_DIR="$HOME/.config/systemd/user"
  SERVICE_FILE="$SERVICE_DIR/aos.service"
  mkdir -p "$SERVICE_DIR"

  cat > "$SERVICE_FILE" << EOF
[Unit]
Description=AOS — Alfred Operating System
After=network.target

[Service]
Type=simple
ExecStart=$(command -v node) ${PROJECT_ROOT}/dist/index.js
WorkingDirectory=${PROJECT_ROOT}
Restart=always
RestartSec=5
Environment=NODE_ENV=production
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
ReadWritePaths=${PROJECT_ROOT}/store ${PROJECT_ROOT}/workspace

[Install]
WantedBy=default.target
EOF

  if systemctl --user daemon-reload 2>/dev/null && \
     systemctl --user enable aos 2>/dev/null; then
    ok "systemd service installed and enabled"
    SYSTEMD_OK=1
  else
    warn "Could not set up systemd service (non-critical)"
    SYSTEMD_OK=0
  fi
fi

# ─── Step 6: Heartbeat cron (Linux/macOS) ─────────

if command -v crontab &>/dev/null; then
  EXISTING_CRON=$(crontab -l 2>/dev/null || true)
  if echo "$EXISTING_CRON" | grep -q "aos/scripts/heartbeat.sh"; then
    ok "Heartbeat monitor already in crontab"
  else
    echo ""
    ANSWER=$(ask "Add heartbeat monitor to crontab? Auto-restarts AOS if it crashes. (Y/n): ")
    if [[ ! "$ANSWER" =~ ^[Nn] ]]; then
      (echo "$EXISTING_CRON"; echo "*/10 * * * * ${PROJECT_ROOT}/scripts/heartbeat.sh") | crontab -
      ok "Heartbeat monitor added (checks every 10 minutes)"
    fi
  fi
fi

# ─── Done ─────────────────────────────────────────

echo ""
echo -e "${BOLD}${GREEN}═══════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN}  Installation complete!${RESET}"
echo -e "${BOLD}${GREEN}═══════════════════════════════════════${RESET}"
echo ""
echo -e "  ${BOLD}What to do now:${RESET}"
echo ""

if [ "${SYSTEMD_OK:-0}" = "1" ]; then
  echo "  1. Start the bot:"
  echo -e "     ${BOLD}systemctl --user start aos${RESET}"
else
  echo "  1. Start the bot:"
  echo -e "     ${BOLD}npm start${RESET}"
fi

echo ""
echo "  2. Open Telegram and send /chatid to your bot"
echo ""
echo "  3. Copy the chat ID and add it to .env:"
echo -e "     ${BOLD}ALLOWED_CHAT_ID=<your_chat_id>${RESET}"
echo ""

if [ "${SYSTEMD_OK:-0}" = "1" ]; then
  echo "  4. Restart to lock it down:"
  echo -e "     ${BOLD}systemctl --user restart aos${RESET}"
else
  echo "  4. Restart the bot (Ctrl+C, then npm start)"
fi

echo ""
echo "  5. Customize CLAUDE.md with your AI's personality"
echo ""
echo "  6. Send a message — you're live!"
echo ""
