#!/usr/bin/env bash
# ═══════════════════════════════════════════════════
# AOS Installer — One command, fully running bot
# ═══════════════════════════════════════════════════
#
# Linux / macOS / WSL:
#   curl -fsSL https://raw.githubusercontent.com/GregMotenJr/aoc/master/install.sh | bash
#
# Windows (PowerShell):
#   irm https://raw.githubusercontent.com/GregMotenJr/aoc/master/install.ps1 | iex

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BOLD='\033[1m'
RESET='\033[0m'

ok()   { echo -e "${GREEN}✓${RESET} $1"; }
warn() { echo -e "${YELLOW}⚠${RESET} $1"; }
fail() { echo -e "${RED}✗${RESET} $1"; exit 1; }
ask()  { read -rp "$1" REPLY </dev/tty; echo "$REPLY"; }

# Resolve project root — BASH_SOURCE[0] is empty when piped via curl | bash,
# so fall back to $0 (also empty in that case) then pwd.
_BASH_SOURCE="${BASH_SOURCE[0]:-}"
if [ -n "$_BASH_SOURCE" ]; then
  PROJECT_ROOT="$(cd "$(dirname "$_BASH_SOURCE")" && pwd)"
else
  PROJECT_ROOT="$(pwd)"
fi
cd "$PROJECT_ROOT"

# ─── Detect OS ────────────────────────────────────

detect_os() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macos"
  elif grep -qi microsoft /proc/version 2>/dev/null; then
    echo "wsl"
  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "linux"
  else
    echo "unknown"
  fi
}

OS=$(detect_os)

echo ""
echo -e "${BOLD}╔═══════════════════════════════════════╗"
echo -e "║   AOS — Alfred Operating System       ║"
echo -e "║   One-command installer                ║"
echo -e "╚═══════════════════════════════════════╝${RESET}"
echo ""

case "$OS" in
  macos)  echo -e "  Platform: ${BOLD}macOS${RESET}" ;;
  linux)  echo -e "  Platform: ${BOLD}Linux${RESET}" ;;
  wsl)    echo -e "  Platform: ${BOLD}Windows (WSL)${RESET}" ;;
  *)      echo -e "  Platform: ${BOLD}Unknown — proceeding as Linux${RESET}" ;;
esac
echo ""

# ─── Step 1: Check prerequisites ──────────────────

echo -e "${BOLD}Checking prerequisites...${RESET}"
echo ""

if ! command -v node &>/dev/null; then
  fail "Node.js not found. Install Node.js 20+ from https://nodejs.org"
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
  fail "Node.js v${NODE_VERSION} found — AOS requires v20 or higher. Update at https://nodejs.org"
fi
ok "Node.js $(node -v)"

if ! command -v npm &>/dev/null; then
  fail "npm not found. It should come with Node.js — reinstall from https://nodejs.org"
fi
ok "npm $(npm -v)"

if command -v claude &>/dev/null; then
  ok "Claude CLI $(claude --version 2>/dev/null || echo 'installed')"
else
  echo ""
  warn "Claude CLI not found."
  echo "  AOS uses Claude Code under the hood. Install it with:"
  echo ""
  echo "    npm install -g @anthropic-ai/claude-code"
  echo ""
  echo "  Then run: claude   (to authenticate)"
  echo ""
  ANSWER=$(ask "Continue anyway? You can install Claude CLI later. (y/N): ")
  if [[ ! "$ANSWER" =~ ^[Yy] ]]; then
    echo "Install Claude CLI first, then re-run ./install.sh"
    exit 0
  fi
fi

# ─── Step 2: Install dependencies ─────────────────

echo ""
echo -e "${BOLD}Installing dependencies...${RESET}"
echo ""
npm install --no-fund --no-audit
ok "Dependencies installed"

# ─── Step 3: Configure .env ───────────────────────

echo ""
echo -e "${BOLD}Configuration${RESET}"
echo ""

SKIP_ENV=0
if [ -f .env ]; then
  echo "  Existing .env file found."
  ANSWER=$(ask "  Overwrite it? (y/N): ")
  if [[ ! "$ANSWER" =~ ^[Yy] ]]; then
    ok "Keeping existing .env"
    SKIP_ENV=1
  fi
fi

if [ "$SKIP_ENV" != "1" ]; then
  echo ""
  echo "  You'll need a Telegram bot token. If you don't have one:"
  echo "  1. Open Telegram and search for @BotFather"
  echo "  2. Send /newbot and follow the prompts"
  echo "  3. Copy the token it gives you"
  echo ""

  BOT_TOKEN=$(ask "  Telegram bot token: ")
  if [ -z "$BOT_TOKEN" ]; then
    fail "Bot token is required. Get one from @BotFather on Telegram."
  fi

  echo ""
  echo "  Optional features (press Enter to skip any):"
  echo ""

  GROQ_KEY=$(ask "  Groq API key (voice transcription — https://console.groq.com): ")
  ELEVENLABS_KEY=$(ask "  ElevenLabs API key (voice replies — https://elevenlabs.io): ")

  ELEVENLABS_VOICE=""
  if [ -n "$ELEVENLABS_KEY" ]; then
    ELEVENLABS_VOICE=$(ask "  ElevenLabs voice ID: ")
  fi

  GOOGLE_KEY=$(ask "  Google API key (video analysis — https://aistudio.google.com): ")

  cat > .env << EOF
# AOS Configuration — generated by install.sh

# Telegram bot token (from @BotFather)
TELEGRAM_BOT_TOKEN=${BOT_TOKEN}

# Your Telegram chat ID
# After starting the bot, send /chatid to it and paste the number here
ALLOWED_CHAT_ID=

# Voice transcription (Groq Whisper) — optional
GROQ_API_KEY=${GROQ_KEY}

# Voice replies (ElevenLabs TTS) — optional
ELEVENLABS_API_KEY=${ELEVENLABS_KEY}
ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE}

# Video analysis (Google Gemini) — optional
GOOGLE_API_KEY=${GOOGLE_KEY}

# Logging
LOG_LEVEL=info
NODE_ENV=production
EOF

  chmod 600 .env
  ok ".env configured"
fi

# ─── Step 4: Build ────────────────────────────────

echo ""
echo -e "${BOLD}Building...${RESET}"
echo ""
npm run build
ok "TypeScript compiled"

# ─── Step 5: Background service ───────────────────

echo ""
echo -e "${BOLD}Setting up background service...${RESET}"
echo ""

SERVICE_OK=0

if [ "$OS" = "macos" ]; then
  # macOS — launchd
  PLIST_DIR="$HOME/Library/LaunchAgents"
  PLIST_FILE="$PLIST_DIR/com.aos.bot.plist"
  mkdir -p "$PLIST_DIR"

  cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.aos.bot</string>
  <key>ProgramArguments</key>
  <array>
    <string>$(command -v node)</string>
    <string>${PROJECT_ROOT}/dist/index.js</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${PROJECT_ROOT}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${PROJECT_ROOT}/store/aos.log</string>
  <key>StandardErrorPath</key>
  <string>${PROJECT_ROOT}/store/aos.error.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>NODE_ENV</key>
    <string>production</string>
  </dict>
</dict>
</plist>
EOF

  if launchctl load "$PLIST_FILE" 2>/dev/null; then
    ok "launchd service installed and loaded (auto-starts on login)"
    SERVICE_OK=1
    SERVICE_START="launchctl start com.aos.bot"
    SERVICE_STOP="launchctl stop com.aos.bot"
    SERVICE_RESTART="launchctl stop com.aos.bot && launchctl start com.aos.bot"
  else
    warn "Could not load launchd service (non-critical)"
  fi

elif [ "$OS" = "linux" ] || [ "$OS" = "wsl" ] || [ "$OS" = "unknown" ]; then
  # Linux / WSL — systemd (user)
  SERVICE_DIR="$HOME/.config/systemd/user"
  SERVICE_FILE="$SERVICE_DIR/aos.service"
  mkdir -p "$SERVICE_DIR"

  cat > "$SERVICE_FILE" << EOF
[Unit]
Description=AOS — Alfred Operating System
After=network.target

[Service]
Type=simple
ExecStart=$(command -v node) "${PROJECT_ROOT}/dist/index.js"
WorkingDirectory=${PROJECT_ROOT}
Restart=always
RestartSec=5
Environment=NODE_ENV=production
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
ReadWritePaths=${PROJECT_ROOT}/store ${PROJECT_ROOT}/workspace

[Install]
WantedBy=default.target
EOF

  if systemctl --user daemon-reload 2>/dev/null && \
     systemctl --user enable aos 2>/dev/null; then
    ok "systemd service installed and enabled (auto-starts on login)"
    SERVICE_OK=1
    SERVICE_START="systemctl --user start aos"
    SERVICE_STOP="systemctl --user stop aos"
    SERVICE_RESTART="systemctl --user restart aos"
  else
    warn "Could not set up systemd service (non-critical)"
  fi
fi

if [ "$SERVICE_OK" = "0" ]; then
  SERVICE_START="npm start"
  SERVICE_STOP="Ctrl+C"
  SERVICE_RESTART="Ctrl+C, then npm start"
fi

# ─── Step 6: Heartbeat cron ───────────────────────

if [ "$OS" != "wsl" ] && command -v crontab &>/dev/null; then
  EXISTING_CRON=$(crontab -l 2>/dev/null || true)
  if echo "$EXISTING_CRON" | grep -qF "$PROJECT_ROOT/scripts/heartbeat.sh"; then
    ok "Heartbeat monitor already in crontab"
  else
    echo ""
    ANSWER=$(ask "Add heartbeat monitor to crontab? Auto-restarts AOS if it crashes. (Y/n): ")
    if [[ ! "$ANSWER" =~ ^[Nn] ]]; then
      (echo "$EXISTING_CRON"; printf '*/10 * * * * "%s/scripts/heartbeat.sh"\n' "$PROJECT_ROOT") | crontab -
      ok "Heartbeat monitor added (checks every 10 minutes)"
    fi
  fi
fi

# ─── Done ─────────────────────────────────────────

echo ""
echo -e "${BOLD}${GREEN}═══════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN}  Installation complete!${RESET}"
echo -e "${BOLD}${GREEN}═══════════════════════════════════════${RESET}"
echo ""
echo -e "  ${BOLD}What to do now:${RESET}"
echo ""
echo "  1. Start the bot:"
echo -e "     ${BOLD}${SERVICE_START}${RESET}"
echo "     (To stop: ${SERVICE_STOP})"
echo ""
echo "  2. Open Telegram and send /chatid to your bot"
echo ""
echo "  3. Copy the chat ID and add it to .env:"
echo -e "     ${BOLD}ALLOWED_CHAT_ID=<your_chat_id>${RESET}"
echo ""
echo "  4. Restart the bot:"
echo -e "     ${BOLD}${SERVICE_RESTART}${RESET}"
echo ""
echo "  5. Customize CLAUDE.md with your AI's personality"
echo ""
echo "  6. Send a message — you're live!"
echo ""
