#!/usr/bin/env tsx

import { execSync, spawnSync } from 'node:child_process';
import {
  existsSync,
  readFileSync,
  writeFileSync,
  chmodSync,
} from 'node:fs';
import { createInterface } from 'node:readline';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');

const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const BOLD = '\x1b[1m';
const RESET = '\x1b[0m';

function ok(msg: string): void {
  console.log(`${GREEN}\u2713${RESET} ${msg}`);
}
function warn(msg: string): void {
  console.log(`${YELLOW}\u26A0${RESET} ${msg}`);
}
function fail(msg: string): void {
  console.log(`${RED}\u2717${RESET} ${msg}`);
}

function ask(prompt: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function main(): Promise<void> {
  console.log(`
${BOLD}╔═══════════════════════════════════╗
║        AOS Setup Wizard          ║
╚═══════════════════════════════════╝${RESET}
`);

  // Check Node.js version
  const nodeVersion = process.version;
  const major = parseInt(nodeVersion.slice(1), 10);
  if (major >= 20) {
    ok(`Node.js ${nodeVersion}`);
  } else {
    fail(`Node.js ${nodeVersion} — requires >= 20`);
    process.exit(1);
  }

  // Check claude CLI
  try {
    const claudeVersion = execSync('claude --version 2>/dev/null', {
      encoding: 'utf-8',
    }).trim();
    ok(`Claude CLI: ${claudeVersion}`);
  } catch {
    fail('Claude CLI not found. Install: npm i -g @anthropic-ai/claude-code');
    process.exit(1);
  }

  // Collect configuration
  console.log(`\n${BOLD}Configuration${RESET}\n`);

  const botToken = await ask('Telegram bot token (from @BotFather): ');
  if (!botToken) {
    fail('Bot token is required');
    process.exit(1);
  }

  const groqKey = await ask('Groq API key (for voice transcription, optional): ');
  const elevenLabsKey = await ask(
    'ElevenLabs API key (for voice replies, optional): ',
  );
  const elevenLabsVoiceId = elevenLabsKey
    ? await ask('ElevenLabs voice ID: ')
    : '';
  const googleKey = await ask(
    'Google API key (for video analysis, optional): ',
  );

  // Write .env
  const envContent = `# AOS Configuration
# Generated by aos setup

# Required — Telegram bot token from @BotFather
TELEGRAM_BOT_TOKEN=${botToken}

# Required after first run — your Telegram chat ID
# Send /chatid to the bot after starting to get this
ALLOWED_CHAT_ID=

# Voice transcription (Groq Whisper)
GROQ_API_KEY=${groqKey}

# Voice replies (ElevenLabs TTS)
ELEVENLABS_API_KEY=${elevenLabsKey}
ELEVENLABS_VOICE_ID=${elevenLabsVoiceId}

# Video analysis (Gemini)
GOOGLE_API_KEY=${googleKey}

# Logging
LOG_LEVEL=info
NODE_ENV=production
`;

  const envPath = join(PROJECT_ROOT, '.env');
  writeFileSync(envPath, envContent, 'utf-8');
  chmodSync(envPath, 0o600);
  ok('.env written (permissions 600)');

  // Build
  console.log(`\n${BOLD}Building...${RESET}\n`);
  const buildResult = spawnSync('npm', ['run', 'build'], {
    cwd: PROJECT_ROOT,
    stdio: 'inherit',
  });
  if (buildResult.status === 0) {
    ok('TypeScript compiled');
  } else {
    fail('Build failed — check errors above');
    process.exit(1);
  }

  // Install systemd service (Linux only)
  if (process.platform === 'linux') {
    console.log(`\n${BOLD}Installing systemd service...${RESET}\n`);

    const serviceDir = join(homedir(), '.config', 'systemd', 'user');
    const servicePath = join(serviceDir, 'aos.service');

    const serviceContent = `[Unit]
Description=AOS — Alfred Operating System
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/node ${join(PROJECT_ROOT, 'dist', 'index.js')}
WorkingDirectory=${PROJECT_ROOT}
Restart=always
RestartSec=5
Environment=NODE_ENV=production

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
ReadWritePaths=${join(PROJECT_ROOT, 'store')} ${join(PROJECT_ROOT, 'workspace')}

[Install]
WantedBy=default.target
`;

    try {
      execSync(`mkdir -p "${serviceDir}"`, { encoding: 'utf-8' });
      writeFileSync(servicePath, serviceContent, 'utf-8');
      execSync('systemctl --user daemon-reload', { encoding: 'utf-8' });
      execSync('systemctl --user enable aos', { encoding: 'utf-8' });
      ok('systemd service installed and enabled');
    } catch (err) {
      warn('Could not install systemd service — install manually');
    }
  }

  // Next steps
  console.log(`
${BOLD}${GREEN}Setup complete!${RESET}

${BOLD}Next steps:${RESET}

1. Start the bot:
   ${BOLD}npm start${RESET}  (or: systemctl --user start aos)

2. Send ${BOLD}/chatid${RESET} to your bot on Telegram

3. Add the chat ID to .env:
   ${BOLD}ALLOWED_CHAT_ID=<your_chat_id>${RESET}

4. Restart: ${BOLD}systemctl --user restart aos${RESET}

5. Customize CLAUDE.md with your personality and context

6. Send a message — you're live!
`);
}

main().catch((err) => {
  fail(`Setup failed: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
